[project]
name = "palindrome-sentences"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "nltk>=3.9.1",
    "torch>=2.5.1",
    "transformers>=4.47.0",
]
